name: CI
permissions:
  contents: write
  issues: write
  pull-requests: write
  id-token: write

on:
  pull_request:

jobs:
  test:
    runs-on: macos-latest
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.GH_SECRET }}
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org/'
          scope: '@trust0'
          cache: 'npm'

      - name: Enable Corepack and set up Yarn
        run: |
          corepack enable
          yarn --version

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Configure npm authentication
        run: |
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ./.npmrc
          echo "@trust0:registry=https://registry.npmjs.org/" >> ./.npmrc
        env:
          NPM_TOKEN: ${{ env.NPM_TOKEN }}

      - name: Install WASM
        env:
          NPM_TOKEN: ${{ env.NPM_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_SECRET }}
        run: |
          curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
          yarn install
          yarn lint
          yarn build
          yarn test
