name: Release
permissions:
  contents: write
  issues: write
  pull-requests: write
  id-token: write

on:
  push:
    branches:
      - main
      - develop
  workflow_dispatch:

jobs:
  release:
    runs-on: macos-latest

    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.GH_SECRET }}
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org/'
          scope: '@trust0'

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Configure npm authentication
        run: |
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ./.npmrc
          echo "@trust0:registry=https://registry.npmjs.org/" >> ./.npmrc

        env:
          NPM_TOKEN: ${{ env.NPM_TOKEN }}

      - name: Run Build package
        env:
          NPM_TOKEN: ${{ env.NPM_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_SECRET }}
        run: |
          npm install
          npm run build

      - name: Release @trust0/ridb-core
        env:
          NPM_TOKEN: ${{ env.NPM_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_SECRET }}
        run: |
          cd packages/ridb-core && npx semantic-release --deps.prefix="^" --tag-format="@trust0/ridb-core@\${version}"

      - name: Release @trust0/ridb
        env:
          NPM_TOKEN: ${{ env.NPM_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_SECRET }}
        run: |
          cd packages/ridb && npx semantic-release --deps.prefix="^" --tag-format="@trust0/ridb@\${version}"
          
      - name: Release @trust0/ridb-level
        env:
          NPM_TOKEN: ${{ env.NPM_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_SECRET }}
        run: |
          cd packages/ridb-level && npx semantic-release --deps.prefix="^" --tag-format="@trust0/ridb-level@\${version}"
          
      - name: Release @trust0/ridb-react
        env:
          NPM_TOKEN: ${{ env.NPM_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_SECRET }}
        run: |
          cd packages/ridb-react && npx semantic-release --deps.prefix="^" --tag-format="@trust0/ridb-react@\${version}"
          
      - name: Update dependencies and commit package.json files
        env:
          GH_TOKEN: ${{ secrets.GH_SECRET }}
        run: |
          git config --global user.name "elribonazo"
          git config --global user.email "elribonazo@gmail.com"
          npm install
          git add package.json package-lock.json
          git commit -m "chore: update dependencies after release [skip ci]" || echo "No changes to commit"
          git push origin ${GITHUB_REF#refs/heads/}